// Biblioteca de Verbos Irregulares en Inglés
// Estructura: { baseForm, pastSimple, pastParticiple, translation, level }

export const bibliotecaIrregularVerbs = [
  // Nivel Sencillo
  { baseForm: 'be', pastSimple: 'was/were', pastParticiple: 'been', translation: 'ser/estar', level: 'sencillo' },
  { baseForm: 'have', pastSimple: 'had', pastParticiple: 'had', translation: 'tener', level: 'sencillo' },
  { baseForm: 'do', pastSimple: 'did', pastParticiple: 'done', translation: 'hacer', level: 'sencillo' },
  { baseForm: 'go', pastSimple: 'went', pastParticiple: 'gone', translation: 'ir', level: 'sencillo' },
  { baseForm: 'see', pastSimple: 'saw', pastParticiple: 'seen', translation: 'ver', level: 'sencillo' },
  { baseForm: 'come', pastSimple: 'came', pastParticiple: 'come', translation: 'venir', level: 'sencillo' },
  { baseForm: 'take', pastSimple: 'took', pastParticiple: 'taken', translation: 'tomar', level: 'sencillo' },
  { baseForm: 'get', pastSimple: 'got', pastParticiple: 'got/gotten', translation: 'obtener', level: 'sencillo' },
  { baseForm: 'make', pastSimple: 'made', pastParticiple: 'made', translation: 'hacer', level: 'sencillo' },
  { baseForm: 'know', pastSimple: 'knew', pastParticiple: 'known', translation: 'saber', level: 'sencillo' },

  // Nivel Medio
  { baseForm: 'eat', pastSimple: 'ate', pastParticiple: 'eaten', translation: 'comer', level: 'medio' },
  { baseForm: 'drink', pastSimple: 'drank', pastParticiple: 'drunk', translation: 'beber', level: 'medio' },
  { baseForm: 'sleep', pastSimple: 'slept', pastParticiple: 'slept', translation: 'dormir', level: 'medio' },
  { baseForm: 'run', pastSimple: 'ran', pastParticiple: 'run', translation: 'correr', level: 'medio' },
  { baseForm: 'write', pastSimple: 'wrote', pastParticiple: 'written', translation: 'escribir', level: 'medio' },
  { baseForm: 'read', pastSimple: 'read', pastParticiple: 'read', translation: 'leer', level: 'medio' },
  { baseForm: 'speak', pastSimple: 'spoke', pastParticiple: 'spoken', translation: 'hablar', level: 'medio' },
  { baseForm: 'break', pastSimple: 'broke', pastParticiple: 'broken', translation: 'romper', level: 'medio' },
  { baseForm: 'choose', pastSimple: 'chose', pastParticiple: 'chosen', translation: 'elegir', level: 'medio' },
  { baseForm: 'find', pastSimple: 'found', pastParticiple: 'found', translation: 'encontrar', level: 'medio' },

  // Nivel Difícil
  { baseForm: 'begin', pastSimple: 'began', pastParticiple: 'begun', translation: 'empezar', level: 'dificil' },
  { baseForm: 'build', pastSimple: 'built', pastParticiple: 'built', translation: 'construir', level: 'dificil' },
  { baseForm: 'buy', pastSimple: 'bought', pastParticiple: 'bought', translation: 'comprar', level: 'dificil' },
  { baseForm: 'catch', pastSimple: 'caught', pastParticiple: 'caught', translation: 'atrapar', level: 'dificil' },
  { baseForm: 'cut', pastSimple: 'cut', pastParticiple: 'cut', translation: 'cortar', level: 'dificil' },
  { baseForm: 'draw', pastSimple: 'drew', pastParticiple: 'drawn', translation: 'dibujar', level: 'dificil' },
  { baseForm: 'drive', pastSimple: 'drove', pastParticiple: 'driven', translation: 'conducir', level: 'dificil' },
  { baseForm: 'fall', pastSimple: 'fell', pastParticiple: 'fallen', translation: 'caer', level: 'dificil' },
  { baseForm: 'feel', pastSimple: 'felt', pastParticiple: 'felt', translation: 'sentir', level: 'dificil' },
  { baseForm: 'fight', pastSimple: 'fought', pastParticiple: 'fought', translation: 'pelear', level: 'dificil' },
  { baseForm: 'fly', pastSimple: 'flew', pastParticiple: 'flown', translation: 'volar', level: 'dificil' },
  { baseForm: 'forget', pastSimple: 'forgot', pastParticiple: 'forgotten', translation: 'olvidar', level: 'dificil' },
  { baseForm: 'give', pastSimple: 'gave', pastParticiple: 'given', translation: 'dar', level: 'dificil' },
  { baseForm: 'grow', pastSimple: 'grew', pastParticiple: 'grown', translation: 'crecer', level: 'dificil' },
  { baseForm: 'hear', pastSimple: 'heard', pastParticiple: 'heard', translation: 'oír', level: 'dificil' },
  { baseForm: 'hide', pastSimple: 'hid', pastParticiple: 'hidden', translation: 'esconder', level: 'dificil' },
  { baseForm: 'hit', pastSimple: 'hit', pastParticiple: 'hit', translation: 'golpear', level: 'dificil' },
  { baseForm: 'hold', pastSimple: 'held', pastParticiple: 'held', translation: 'sostener', level: 'dificil' },
  { baseForm: 'keep', pastSimple: 'kept', pastParticiple: 'kept', translation: 'mantener', level: 'dificil' },
  { baseForm: 'leave', pastSimple: 'left', pastParticiple: 'left', translation: 'dejar', level: 'dificil' },
  { baseForm: 'lend', pastSimple: 'lent', pastParticiple: 'lent', translation: 'prestar', level: 'dificil' },
  { baseForm: 'let', pastSimple: 'let', pastParticiple: 'let', translation: 'dejar', level: 'dificil' },
  { baseForm: 'lie', pastSimple: 'lay', pastParticiple: 'lain', translation: 'mentir', level: 'dificil' },
  { baseForm: 'lose', pastSimple: 'lost', pastParticiple: 'lost', translation: 'perder', level: 'dificil' },
  { baseForm: 'meet', pastSimple: 'met', pastParticiple: 'met', translation: 'conocer', level: 'dificil' },
  { baseForm: 'pay', pastSimple: 'paid', pastParticiple: 'paid', translation: 'pagar', level: 'dificil' },
  { baseForm: 'put', pastSimple: 'put', pastParticiple: 'put', translation: 'poner', level: 'dificil' },
  { baseForm: 'ride', pastSimple: 'rode', pastParticiple: 'ridden', translation: 'montar', level: 'dificil' },
  { baseForm: 'ring', pastSimple: 'rang', pastParticiple: 'rung', translation: 'llamar', level: 'dificil' },
  { baseForm: 'rise', pastSimple: 'rose', pastParticiple: 'risen', translation: 'levantarse', level: 'dificil' },
  { baseForm: 'say', pastSimple: 'said', pastParticiple: 'said', translation: 'decir', level: 'dificil' },
  { baseForm: 'sell', pastSimple: 'sold', pastParticiple: 'sold', translation: 'vender', level: 'dificil' },
  { baseForm: 'send', pastSimple: 'sent', pastParticiple: 'sent', translation: 'enviar', level: 'dificil' },
  { baseForm: 'shine', pastSimple: 'shone', pastParticiple: 'shone', translation: 'brillar', level: 'dificil' },
  { baseForm: 'shoot', pastSimple: 'shot', pastParticiple: 'shot', translation: 'disparar', level: 'dificil' },
  { baseForm: 'show', pastSimple: 'showed', pastParticiple: 'shown', translation: 'mostrar', level: 'dificil' },
  { baseForm: 'shut', pastSimple: 'shut', pastParticiple: 'shut', translation: 'cerrar', level: 'dificil' },
  { baseForm: 'sing', pastSimple: 'sang', pastParticiple: 'sung', translation: 'cantar', level: 'dificil' },
  { baseForm: 'sit', pastSimple: 'sat', pastParticiple: 'sat', translation: 'sentarse', level: 'dificil' },
  { baseForm: 'stand', pastSimple: 'stood', pastParticiple: 'stood', translation: 'estar de pie', level: 'dificil' },
  { baseForm: 'steal', pastSimple: 'stole', pastParticiple: 'stolen', translation: 'robar', level: 'dificil' },
  { baseForm: 'swim', pastSimple: 'swam', pastParticiple: 'swum', translation: 'nadar', level: 'dificil' },
  { baseForm: 'teach', pastSimple: 'taught', pastParticiple: 'taught', translation: 'enseñar', level: 'dificil' },
  { baseForm: 'tell', pastSimple: 'told', pastParticiple: 'told', translation: 'decir', level: 'dificil' },
  { baseForm: 'think', pastSimple: 'thought', pastParticiple: 'thought', translation: 'pensar', level: 'dificil' },
  { baseForm: 'throw', pastSimple: 'threw', pastParticiple: 'thrown', translation: 'lanzar', level: 'dificil' },
  { baseForm: 'understand', pastSimple: 'understood', pastParticiple: 'understood', translation: 'entender', level: 'dificil' },
  { baseForm: 'wake', pastSimple: 'woke', pastParticiple: 'woken', translation: 'despertar', level: 'dificil' },
  { baseForm: 'wear', pastSimple: 'wore', pastParticiple: 'worn', translation: 'llevar puesto', level: 'dificil' },
  { baseForm: 'win', pastSimple: 'won', pastParticiple: 'won', translation: 'ganar', level: 'dificil' },
  { baseForm: 'write', pastSimple: 'wrote', pastParticiple: 'written', translation: 'escribir', level: 'dificil' },
];