export const BANCO_EAE = {
    GENERAL: [
        { p: 'MESA', t: ['silla', 'comer', 'mueble', 'patas', 'madera'] },
        { p: 'SILLA', t: ['sentarse', 'mesa', 'mueble', 'respaldo', 'cuatro'] },
        { p: 'PERRO', t: ['gato', 'ladrar', 'animal', 'mascota', 'hueso'] },
        { p: 'GATO', t: ['perro', 'maullar', 'ratón', 'mascota', 'felino'] },
        { p: 'CASA', t: ['vivir', 'hogar', 'puerta', 'techo', 'edificio'] },
        { p: 'COCHE', t: ['conducir', 'ruedas', 'vehículo', 'carretera', 'motor'] },
        { p: 'ARBOL', t: ['hojas', 'ramas', 'bosque', 'naturaleza', 'tronco'] },
        { p: 'SOL', t: ['luna', 'brillar', 'calor', 'estrella', 'cielo'] },
        { p: 'LUNA', t: ['sol', 'noche', 'blanca', 'cielo', 'estrellas'] },
        { p: 'AGUA', t: ['beber', 'líquido', 'sed', 'grifo', 'mar'] },
        { p: 'FUEGO', t: ['calor', 'quemar', 'incendio', 'llama', 'rojo'] },
        { p: 'LIBRO', t: ['leer', 'páginas', 'papel', 'biblioteca', 'letras'] },
        { p: 'ZAPATO', t: ['pie', 'caminar', 'calcetín', 'calzado', 'cordones'] },
        { p: 'RELOJ', t: ['hora', 'tiempo', 'muñeca', 'manecillas', 'tic-tac'] },
        { p: 'CAMA', t: ['dormir', 'colchón', 'almohada', 'sábana', 'habitación'] },
        { p: 'PUERTA', t: ['abrir', 'cerrar', 'entrar', 'llave', 'madera'] },
        { p: 'VENTANA', t: ['cristal', 'mirar', 'luz', 'abrir', 'casa'] },
        { p: 'TELEFONO', t: ['llamar', 'hablar', 'móvil', 'número', 'comunicar'] },
        { p: 'GAFAS', t: ['ojos', 'ver', 'vista', 'cristales', 'leer'] },
        { p: 'SOMBRERO', t: ['cabeza', 'sol', 'poner', 'gorra', 'pelo'] },
        { p: 'CUCHARA', t: ['sopa', 'comer', 'tenedor', 'cubierto', 'boca'] },
        { p: 'TENEDOR', t: ['pinchar', 'comer', 'cuchillo', 'cubierto', 'carne'] },
        { p: 'PLATO', t: ['comida', 'redondo', 'vaso', 'mesa', 'servir'] },
        { p: 'VASO', t: ['agua', 'beber', 'cristal', 'líquido', 'taza'] },
        { p: 'LLAVE', t: ['puerta', 'abrir', 'cerradura', 'metal', 'entrar'] }
    ],
    MATEMATICAS: [
        { p: 'CIRCULO', t: ['redondo', 'esfera', 'figura', 'curva', 'compás'] },
        { p: 'CUADRADO', t: ['cuatro', 'lados', 'cubo', 'figura', 'iguales'] },
        { p: 'TRIANGULO', t: ['tres', 'lados', 'puntas', 'pirámide', 'figura'] },
        { p: 'RECTANGULO', t: ['lados', 'cuadrado', 'largo', 'figura', 'caja'] },
        { p: 'NUMERO', t: ['contar', 'matemáticas', 'cifra', 'suma', 'cantidad'] },
        { p: 'SUMA', t: ['más', 'añadir', 'juntar', 'resta', 'operación'] },
        { p: 'RESTA', t: ['menos', 'quitar', 'suma', 'perder', 'operación'] },
        { p: 'MULTIPLICACION', t: ['por', 'tabla', 'veces', 'división', 'operación'] },
        { p: 'DIVISION', t: ['repartir', 'partes', 'multiplicación', 'fracción', 'entre'] },
        { p: 'FRACCION', t: ['partir', 'mitad', 'numerador', 'denominador', 'porción'] },
        { p: 'PORCENTAJE', t: ['cien', 'descuento', 'símbolo', 'rebaja', 'cálculo'] },
        { p: 'ANGULO', t: ['grados', 'esquina', 'recto', 'agudo', 'obtuso'] },
        { p: 'REGLA', t: ['medir', 'línea', 'recta', 'centímetros', 'dibujar'] },
        { p: 'COMPAS', t: ['círculo', 'dibujar', 'pinchar', 'redondo', 'herramienta'] },
        { p: 'CALCULADORA', t: ['botones', 'cuenta', 'máquina', 'números', 'resultado'] },
        { p: 'CERO', t: ['nada', 'vacío', 'número', 'redondo', 'nulo'] },
        { p: 'INFINITO', t: ['ocho', 'acabar', 'siempre', 'límite', 'símbolo'] },
        { p: 'GEOMETRIA', t: ['formas', 'figuras', 'dibujo', 'espacio', 'matemáticas'] },
        { p: 'ALGEBRA', t: ['letras', 'equis', 'ecuación', 'incógnita', 'despejar'] },
        { p: 'ECUACION', t: ['igual', 'despejar', 'incógnita', 'álgebra', 'resolver'] },
        { p: 'IGUAL', t: ['resultado', 'rayas', 'símbolo', 'mismo', 'equivalente'] },
        { p: 'PAR', t: ['dos', 'impar', 'divisible', 'gemelos', 'número'] },
        { p: 'IMPAR', t: ['par', 'uno', 'tres', 'cinco', 'divisible'] },
        { p: 'DECIMAL', t: ['coma', 'punto', 'entero', 'fracción', 'cifra'] },
        { p: 'RADIO', t: ['círculo', 'centro', 'mitad', 'diámetro', 'circunferencia'] }
    ],
    LENGUA: [
        { p: 'VERBO', t: ['acción', 'palabra', 'hacer', 'tiempo', 'conjugar'] },
        { p: 'SUSTANTIVO', t: ['nombre', 'cosa', 'animal', 'persona', 'palabra'] },
        { p: 'ADJETIVO', t: ['cualidad', 'describir', 'sustantivo', 'bonito', 'palabra'] },
        { p: 'CUENTO', t: ['historia', 'niños', 'leer', 'libro', 'había'] },
        { p: 'POESIA', t: ['rimar', 'versos', 'poema', 'escribir', 'estrofa'] },
        { p: 'NOVELA', t: ['libro', 'largo', 'historia', 'leer', 'capítulos'] },
        { p: 'PUNTO', t: ['final', 'oración', 'coma', 'signo', 'terminar'] },
        { p: 'COMA', t: ['pausa', 'respirar', 'punto', 'signo', 'lista'] },
        { p: 'EXCLAMACION', t: ['gritar', 'sorpresa', 'signo', 'admiración', 'emoción'] },
        { p: 'INTERROGACION', t: ['pregunta', 'duda', 'signo', 'responder', 'qué'] },
        { p: 'DICCIONARIO', t: ['significado', 'palabras', 'buscar', 'libro', 'definición'] },
        { p: 'LETRA', t: ['abecedario', 'escribir', 'palabra', 'vocal', 'consonante'] },
        { p: 'ABECEDARIO', t: ['letras', 'alfabeto', 'orden', 'zeta', 'consonantes'] },
        { p: 'VOCAL', t: ['a', 'e', 'i', 'o', 'u'] },
        { p: 'CONSONANTE', t: ['vocal', 'letra', 'alfabeto', 'sonido', 'abecedario'] },
        { p: 'SILABA', t: ['golpe', 'voz', 'separar', 'palabra', 'acento'] },
        { p: 'SINONIMO', t: ['igual', 'parecido', 'significado', 'antónimo', 'palabra'] },
        { p: 'ANTONIMO', t: ['contrario', 'opuesto', 'sinónimo', 'significado', 'diferente'] },
        { p: 'RESUMEN', t: ['corto', 'texto', 'idea', 'principal', 'reducir'] },
        { p: 'METAFORA', t: ['figura', 'comparar', 'poesía', 'sentido', 'literal'] },
        { p: 'RIMA', t: ['poesía', 'sonar', 'igual', 'final', 'canción'] },
        { p: 'TITULO', t: ['nombre', 'libro', 'portada', 'encabezado', 'obra'] },
        { p: 'AUTOR', t: ['escribir', 'creador', 'libro', 'escritor', 'obra'] },
        { p: 'PROTAGONISTA', t: ['principal', 'personaje', 'historia', 'bueno', 'héroe'] },
        { p: 'PARRAFO', t: ['texto', 'punto', 'aparte', 'líneas', 'sangría'] }
    ],
    HISTORIA: [
        { p: 'ROMA', t: ['italia', 'imperio', 'gladiador', 'césar', 'coliseo'] },
        { p: 'EGIPTO', t: ['pirámide', 'faraón', 'momia', 'nilo', 'desierto'] },
        { p: 'PIRAMIDE', t: ['egipto', 'faraón', 'triángulo', 'momia', 'desierto'] },
        { p: 'REY', t: ['corona', 'reina', 'monarca', 'castillo', 'trono'] },
        { p: 'REINA', t: ['rey', 'corona', 'princesa', 'castillo', 'trono'] },
        { p: 'CASTILLO', t: ['rey', 'medieval', 'torre', 'fortaleza', 'piedra'] },
        { p: 'GUERRA', t: ['paz', 'luchar', 'batalla', 'armas', 'soldados'] },
        { p: 'PAZ', t: ['guerra', 'tranquilidad', 'paloma', 'blanca', 'acuerdo'] },
        { p: 'COLON', t: ['cristóbal', 'américa', 'descubrir', 'barcos', 'carabelas'] },
        { p: 'IMPERIO', t: ['emperador', 'conquistar', 'roma', 'territorio', 'rey'] },
        { p: 'PREHISTORIA', t: ['dinosaurios', 'cavernícolas', 'historia', 'fuego', 'piedra'] },
        { p: 'DINOSAURIO', t: ['extinto', 'animal', 'prehistoria', 'trex', 'jurásico'] },
        { p: 'CAVERNICOLA', t: ['cueva', 'prehistoria', 'fuego', 'piedra', 'club'] },
        { p: 'GLADIADOR', t: ['roma', 'coliseo', 'luchar', 'espada', 'arena'] },
        { p: 'CABALLERO', t: ['armadura', 'caballo', 'espada', 'medieval', 'castillo'] },
        { p: 'CORONA', t: ['rey', 'cabeza', 'oro', 'joyas', 'princesa'] },
        { p: 'ESPADA', t: ['arma', 'caballero', 'cortar', 'luchar', 'metal'] },
        { p: 'ESCUDO', t: ['proteger', 'espada', 'caballero', 'arma', 'defender'] },
        { p: 'REVOLUCION', t: ['francesa', 'cambio', 'pueblo', 'industrial', 'guerra'] },
        { p: 'FARAON', t: ['egipto', 'rey', 'pirámide', 'momia', 'nilo'] },
        { p: 'MOMIA', t: ['egipto', 'vendas', 'muerto', 'sarcófago', 'pirámide'] },
        { p: 'CRISTIANISMO', t: ['religión', 'jesús', 'iglesia', 'cruz', 'biblia'] },
        { p: 'ISLAM', t: ['religión', 'musulmán', 'mahoma', 'mezquita', 'corán'] },
        { p: 'BRUJULA', t: ['norte', 'navegar', 'barco', 'orientarse', 'imán'] },
        { p: 'CARABELA', t: ['barco', 'colón', 'pinta', 'niña', 'santamaría'] }
    ],
    DEPORTE: [
        { p: 'FUTBOL', t: ['balón', 'portería', 'gol', 'pie', 'equipo'] },
        { p: 'BALONCESTO', t: ['canasta', 'mano', 'botar', 'equipo', 'alto'] },
        { p: 'TENIS', t: ['raqueta', 'red', 'pelota', 'nadal', 'pista'] },
        { p: 'NATACION', t: ['agua', 'piscina', 'nadar', 'bañador', 'estilos'] },
        { p: 'ATLETISMO', t: ['correr', 'pista', 'saltar', 'carrera', 'olimpiadas'] },
        { p: 'BALON', t: ['fútbol', 'pelota', 'esfera', 'chutar', 'redondo'] },
        { p: 'RAQUETA', t: ['tenis', 'padel', 'golpear', 'pelota', 'red'] },
        { p: 'PORTERIA', t: ['gol', 'fútbol', 'red', 'portero', 'marcar'] },
        { p: 'CANASTA', t: ['baloncesto', 'aro', 'red', 'encestar', 'puntos'] },
        { p: 'GOL', t: ['fútbol', 'marcar', 'portería', 'punto', 'gritar'] },
        { p: 'ARBITRO', t: ['pitar', 'tarjeta', 'falta', 'negro', 'juez'] },
        { p: 'MEDALLA', t: ['oro', 'plata', 'bronce', 'ganar', 'cuello'] },
        { p: 'TROFEO', t: ['copa', 'ganar', 'premio', 'campeón', 'torneo'] },
        { p: 'ESTADIO', t: ['gradas', 'campo', 'fútbol', 'público', 'partido'] },
        { p: 'EQUIPO', t: ['jugadores', 'compañeros', 'grupo', 'camiseta', 'jugar'] },
        { p: 'ENTRENADOR', t: ['míster', 'dirigir', 'equipo', 'táctica', 'banquillo'] },
        { p: 'PISCINA', t: ['agua', 'nadar', 'natación', 'bañador', 'cloro'] },
        { p: 'CORRER', t: ['rápido', 'piernas', 'atletismo', 'carrera', 'maratón'] },
        { p: 'SALTAR', t: ['aire', 'arriba', 'altura', 'longitud', 'pértiga'] },
        { p: 'BICICLETA', t: ['pedales', 'ruedas', 'ciclismo', 'montar', 'manillar'] },
        { p: 'CICLISMO', t: ['bicicleta', 'pedalear', 'tour', 'vuelta', 'corredor'] },
        { p: 'BOXEO', t: ['guantes', 'ring', 'pegar', 'combate', 'puñetazo'] },
        { p: 'GUANTE', t: ['mano', 'boxeo', 'portero', 'frío', 'dedos'] },
        { p: 'RED', t: ['tenis', 'voleibol', 'medio', 'malla', 'separar'] },
        { p: 'OLIMPIADAS', t: ['juegos', 'anillos', 'medallas', 'cada', 'cuatro'] }
    ],
    ARTE_MUSICA: [
        { p: 'PINTURA', t: ['cuadro', 'pincel', 'color', 'arte', 'dibujar'] },
        { p: 'PINCEL', t: ['pintar', 'pelo', 'brocha', 'acuarela', 'lienzo'] },
        { p: 'LIENZO', t: ['pintar', 'tela', 'blanco', 'cuadro', 'caballete'] },
        { p: 'COLOR', t: ['rojo', 'azul', 'amarillo', 'pintar', 'arcoíris'] },
        { p: 'CUADRO', t: ['pintura', 'pared', 'marco', 'museo', 'obra'] },
        { p: 'ESCULTURA', t: ['estatua', 'piedra', 'esculpir', 'barro', 'arte'] },
        { p: 'MUSEO', t: ['cuadros', 'exposición', 'arte', 'visitar', 'prado'] },
        { p: 'MUSICA', t: ['escuchar', 'canción', 'instrumentos', 'sonido', 'tocar'] },
        { p: 'GUITARRA', t: ['cuerdas', 'tocar', 'flamenco', 'púa', 'instrumento'] },
        { p: 'PIANO', t: ['teclas', 'blanco', 'negro', 'tocar', 'instrumento'] },
        { p: 'TAMBOR', t: ['golpear', 'percusión', 'palillos', 'ruido', 'instrumento'] },
        { p: 'FLAUTA', t: ['soplar', 'agujeros', 'instrumento', 'viento', 'boca'] },
        { p: 'VIOLIN', t: ['cuerdas', 'arco', 'barbilla', 'orquesta', 'instrumento'] },
        { p: 'CANTAR', t: ['voz', 'canción', 'música', 'micrófono', 'afinar'] },
        { p: 'CANCION', t: ['cantar', 'música', 'letra', 'escuchar', 'radio'] },
        { p: 'CANTANTE', t: ['voz', 'cantar', 'concierto', 'micrófono', 'grupo'] },
        { p: 'BANDA', t: ['grupo', 'música', 'concierto', 'instrumentos', 'rock'] },
        { p: 'ORQUESTA', t: ['director', 'músicos', 'clásica', 'violín', 'instrumentos'] },
        { p: 'NOTA', t: ['do', 're', 'mi', 'partitura', 'música'] },
        { p: 'PARTITURA', t: ['papel', 'notas', 'leer', 'música', 'pentagrama'] },
        { p: 'MICROFONO', t: ['cantar', 'voz', 'amplificar', 'hablar', 'cantante'] },
        { p: 'ESCENARIO', t: ['teatro', 'actuar', 'público', 'luces', 'concierto'] },
        { p: 'TEATRO', t: ['actores', 'obra', 'escenario', 'público', 'telón'] },
        { p: 'ACTOR', t: ['película', 'teatro', 'actuar', 'personaje', 'cine'] },
        { p: 'BAILAR', t: ['moverse', 'ritmo', 'música', 'danza', 'pies'] }
    ],
    GEOGRAFIA: [
        { p: 'MONTAÑA', t: ['alto', 'pico', 'nieve', 'escalar', 'cordillera'] },
        { p: 'RIO', t: ['agua', 'corriente', 'mar', 'desembocar', 'cauce'] },
        { p: 'MAR', t: ['agua', 'salada', 'playa', 'océano', 'olas'] },
        { p: 'OCEANO', t: ['mar', 'grande', 'atlántico', 'pacífico', 'agua'] },
        { p: 'PLAYA', t: ['arena', 'mar', 'verano', 'sol', 'bañarse'] },
        { p: 'ISLA', t: ['agua', 'rodeada', 'mar', 'palmera', 'tierra'] },
        { p: 'VOLCAN', t: ['lava', 'montaña', 'erupción', 'fuego', 'ceniza'] },
        { p: 'DESIERTO', t: ['arena', 'calor', 'seco', 'camello', 'oasis'] },
        { p: 'BOSQUE', t: ['árboles', 'naturaleza', 'animales', 'verde', 'hojas'] },
        { p: 'MAPA', t: ['países', 'mundo', 'papel', 'buscar', 'geografía'] },
        { p: 'NORTE', t: ['sur', 'arriba', 'brújula', 'dirección', 'polo'] },
        { p: 'SUR', t: ['norte', 'abajo', 'brújula', 'dirección', 'polo'] },
        { p: 'ESPAÑA', t: ['país', 'madrid', 'península', 'europa', 'nuestro'] },
        { p: 'FRANCIA', t: ['parís', 'país', 'vecino', 'torre', 'eiffel'] },
        { p: 'ITALIA', t: ['bota', 'roma', 'pasta', 'pizza', 'país'] },
        { p: 'MADRID', t: ['capital', 'españa', 'ciudad', 'centro', 'oso'] },
        { p: 'PARIS', t: ['capital', 'francia', 'torre', 'eiffel', 'ciudad'] },
        { p: 'LONDRES', t: ['capital', 'inglaterra', 'reloj', 'big', 'ben'] },
        { p: 'EUROPA', t: ['continente', 'españa', 'países', 'unión', 'mapa'] },
        { p: 'AMERICA', t: ['continente', 'norte', 'sur', 'colón', 'estados'] },
        { p: 'TIERRA', t: ['planeta', 'mundo', 'suelo', 'sol', 'redonda'] },
        { p: 'PLANETA', t: ['tierra', 'marte', 'sistema', 'solar', 'espacio'] },
        { p: 'CONTINENTE', t: ['europa', 'américa', 'áfrica', 'asia', 'oceanía'] },
        { p: 'FRONTERA', t: ['límite', 'separar', 'país', 'cruzar', 'línea'] },
        { p: 'CORDILLERA', t: ['montañas', 'conjunto', 'picos', 'himalaya', 'sierra'] }
    ],
    TECNOLOGIA: [
        { p: 'ORDENADOR', t: ['teclado', 'ratón', 'pantalla', 'internet', 'jugar'] },
        { p: 'RATON', t: ['ordenador', 'clic', 'pantalla', 'animal', 'teclado'] },
        { p: 'TECLADO', t: ['letras', 'escribir', 'ordenador', 'botones', 'ratón'] },
        { p: 'PANTALLA', t: ['ver', 'televisión', 'ordenador', 'móvil', 'cristal'] },
        { p: 'INTERNET', t: ['red', 'wifi', 'ordenador', 'conectar', 'web'] },
        { p: 'WIFI', t: ['internet', 'inalámbrico', 'conexión', 'contraseña', 'red'] },
        { p: 'ROBOT', t: ['máquina', 'metálico', 'inteligencia', 'programar', 'humanoide'] },
        { p: 'CABLE', t: ['enchufar', 'corriente', 'hilo', 'conectar', 'electricidad'] },
        { p: 'BATERIA', t: ['pila', 'cargar', 'móvil', 'energía', 'porcentaje'] },
        { p: 'TELEVISION', t: ['ver', 'canales', 'pantalla', 'mando', 'programas'] },
        { p: 'RADIO', t: ['escuchar', 'música', 'coche', 'emisora', 'antena'] },
        { p: 'NEVERA', t: ['frío', 'comida', 'cocina', 'congelador', 'electrodoméstico'] },
        { p: 'LAVADORA', t: ['ropa', 'limpiar', 'jabón', 'dar', 'vueltas'] },
        { p: 'MICROONDAS', t: ['calentar', 'comida', 'cocina', 'rápido', 'electrodoméstico'] },
        { p: 'CAMARA', t: ['fotos', 'vídeo', 'hacer', 'imagen', 'objetivo'] },
        { p: 'FOTO', t: ['cámara', 'imagen', 'recuerdo', 'selfie', 'sonreír'] },
        { p: 'VIDEO', t: ['grabar', 'cámara', 'imagen', 'movimiento', 'youtube'] },
        { p: 'AVION', t: ['volar', 'cielo', 'alas', 'aeropuerto', 'pasajeros'] },
        { p: 'TREN', t: ['vías', 'estación', 'vagones', 'viajar', 'ferrocarril'] },
        { p: 'ELECTRICIDAD', t: ['luz', 'corriente', 'enchufe', 'cable', 'energía'] },
        { p: 'BOMBILLA', t: ['luz', 'encender', 'lámpara', 'cristal', 'edison'] },
        { p: 'INVENTO', t: ['crear', 'descubrir', 'nuevo', 'máquina', 'idea'] },
        { p: 'PROGRAMA', t: ['ordenador', 'software', 'aplicación', 'código', 'instalar'] },
        { p: 'IMPRESORA', t: ['papel', 'tinta', 'ordenador', 'imprimir', 'documento'] },
        { p: 'TABLET', t: ['ipad', 'pantalla', 'táctil', 'ordenador', 'móvil'] }
    ]
};

export const CATEGORIAS_EAE = [
    { id: 'TODAS',       label: '🌐 Todas las categorías' },
    { id: 'GENERAL',     label: '🎯 General' },
    { id: 'MATEMATICAS', label: '📐 Matemáticas' },
    { id: 'LENGUA',      label: '📝 Lengua' },
    { id: 'HISTORIA',    label: '🏛️ Historia' },
    { id: 'DEPORTE',     label: '⚽ Deporte' },
    { id: 'ARTE_MUSICA', label: '🎨 Arte y Música' },
    { id: 'GEOGRAFIA',   label: '🌍 Geografía' },
    { id: 'TECNOLOGIA',  label: '💻 Tecnología' },
];

export function getPalabrasEAE(categoriaId = 'TODAS') {
    if (categoriaId === 'TODAS') return Object.values(BANCO_EAE).flat();
    return BANCO_EAE[categoriaId] || BANCO_EAE.GENERAL;
}